
if (ANDROID)
    if (${CONFIG} MATCHES "arm32")
        set(ION_LIB_DIR "${CMAKE_CURRENT_SOURCE_DIR}/3rdparty/ion/lib")
    elseif (${CONFIG} MATCHES "arm64")
        set(ION_LIB_DIR "${CMAKE_CURRENT_SOURCE_DIR}/3rdparty/ion/lib64")
    endif ()
    set(ION_INCLUDE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/3rdparty/ion/include")
    include_directories(${ION_INCLUDE_PATH})
elseif (LINUX)
    if (${CONFIG} MATCHES "arm32")
        set(ION_LIB_DIR "${CMAKE_CURRENT_SOURCE_DIR}/3rdparty/ion/lib")
    elseif (${CONFIG} MATCHES "arm64")
        set(ION_LIB_DIR "${CMAKE_CURRENT_SOURCE_DIR}/3rdparty/ion/lib64")
    endif ()
    set(ION_INCLUDE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/3rdparty/ion/include")
    set(ION_INCLUDE_LINUX_PATH "${CMAKE_CURRENT_SOURCE_DIR}/3rdparty/ion/include/linux")
    include_directories(${ION_INCLUDE_PATH})
    include_directories(${ION_INCLUDE_LINUX_PATH})
endif ()

link_directories(${ION_LIB_DIR})
link_libraries("ion")
install(FILES "${ION_LIB_DIR}/libion.so" DESTINATION ../lib/3rdparty/ion)

message(STATUS "CONFIG = ${CONFIG}")
message(STATUS "ION_INCLUDE_PATH = ${ION_INCLUDE_PATH}")
message(STATUS "ION_INCLUDE_LINUX_PATH = ${ION_INCLUDE_LINUX_PATH}")
message(STATUS "ION_LIB_DIR = ${ION_LIB_DIR}")
